fix: import with file extensions
Recent versions of TypeScript don't implicitly add `.js` onto file
imports so it's necssary to specify them.

Fixes `tsc` errors like the below when types from this module are
referenced using `typescript@6`+

```
src/document-check.js:77:81 - error TS7006: Parameter 'code' implicitly has an 'any' type.

77                   const diagnosticCodes = result.error?.diagnosticCodes?.filter(code => !TS_ERRORS_TO_SUPPRESS.includes(code))
```